services:
  mysql-econome-pedidos:
    image: 'mysql:8.0'
    volumes:
      - ./mysql-data-pedidos:/var/lib/mysql
    environment:
      - 'MYSQL_DATABASE=econome_db_pedidos'
      - 'MYSQL_ROOT_PASSWORD=12345'
      - TZ=America/Sao_Paulo
    ports:
      - '3306:3306'

  app-econome-pedidos:
    build: .
    depends_on:
      - mysql-econome-pedidos
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-econome-pedidos:3306/econome_db_pedidos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_LIQUIBASE_ENABLED: 'true'
    ports:
      - '8080:8080'

# Rede padrão do Docker Compose será usada para comunicação entre app e banco
