services:
  mysql-econome-pedidos:
    image: 'mysql:8.0'
    volumes:
      - ./mysql-data-pedidos:/var/lib/mysql
    environment:
      - 'MYSQL_DATABASE=econome_db_pedidos'
      - 'MYSQL_ROOT_PASSWORD=12345'
      - TZ=America/Sao_Paulo
    ports:
      - '3306:3306'
    networks:
      - econome-net

  app-econome-pedidos:
    build: .
    depends_on:
      - mysql-econome-pedidos
    environment:
      # Hostname do serviço de transações na rede externa econome-net
      TRANSACOES_API_BASE_URL: ${TRANSACOES_API_BASE_URL}
    ports:
      - '8080:8080'
    networks:
      - econome-net

networks:
  econome-net:
    external: true
