services:
  mysql-econome-pedidos:
    image: 'mysql:8.0'
    volumes:
      - ./mysql-data-pedidos:/var/lib/mysql
    environment:
      - 'MYSQL_DATABASE=econome_db_pedidos'
      - 'MYSQL_ROOT_PASSWORD=12345'
      - TZ=America/Sao_Paulo
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 15
    networks:
      - econome-net

  app-econome-pedidos:
    build: .
    depends_on:
      mysql-econome-pedidos:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_LIQUIBASE_ENABLED: ${SPRING_LIQUIBASE_ENABLED}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      # Hostname do serviço de transações na rede externa econome-net
      TRANSACOES_API_BASE_URL: ${TRANSACOES_API_BASE_URL}
    ports:
      - '8080:8080'
    networks:
      - econome-net

networks:
  econome-net:
    external: true
