spring:
  application:
    name: app-econome-pedidos
  datasource:
    url: jdbc:mysql://localhost:3306/econome_db_pedidos?useUnicode=true&characterEncoding=utf8&useSSL=false&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: '12345'
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:config/liquibase/db.changelog-master.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

transacoes:
  api:
    base-url: http://localhost:5001 # URL do microserviço de transações (Flask)
    enabled: true # Permite desligar integração sem recompilar
